// قاموس ترجمة للكلمات العربية والإنجليزية للمكونات
export const arabicToEnglishMapping: Record<string, string[]> = {
  // مكونات أساسية
  'أكورديون': ['accordion', 'collapsible', 'expandable'],
  'زر': ['button', 'btn'],
  'نص': ['text', 'typography', 'label'],
  'حقل': ['input', 'field', 'form'],
  'قائمة': ['list', 'menu', 'dropdown'],
  'جدول': ['table', 'grid'],
  'بطاقة': ['card', 'panel'],
  'نافذة': ['modal', 'dialog', 'popup'],
  'تنبيه': ['alert', 'notification', 'toast'],
  'شريط': ['bar', 'progress', 'slider'],
  'تبويب': ['tab', 'tabs'],
  'نموذج': ['form', 'formulary'],
  'تسجيل': ['login', 'signin', 'auth'],
  'تسجيل الدخول': ['login', 'signin', 'auth'],
  'تسجيل الخروج': ['logout', 'signout'],
  'تسجيل جديد': ['signup', 'register', 'signup'],
  'ملف': ['file', 'upload', 'document'],
  'صورة': ['image', 'picture', 'photo'],
  'فيديو': ['video', 'media'],
  'صوت': ['audio', 'sound'],
  'رابط': ['link', 'anchor'],
  'قائمة منسدلة': ['dropdown', 'select', 'combobox'],
  'شريط التمرير': ['scrollbar', 'scroll'],
  'شريط التنقل': ['navbar', 'navigation', 'nav'],
  'شريط جانبي': ['sidebar', 'aside'],
  'تذييل': ['footer'],
  'رأس': ['header', 'head'],
  'محتوى': ['content', 'body'],
  'حاوية': ['container', 'wrapper'],
  'شبكة': ['grid', 'layout'],
  'صف': ['row'],
  'عمود': ['column', 'col'],
  'فاصل': ['divider', 'separator'],
  'أيقونة': ['icon'],
  'شعار': ['logo'],
  'علامة': ['badge', 'tag', 'label'],
  'تلميح': ['tooltip', 'hint'],
  'تأكيد': ['confirmation', 'confirm'],
  'حذف': ['delete', 'remove'],
  'تحرير': ['edit', 'modify'],
  'حفظ': ['save', 'store'],
  'إلغاء': ['cancel', 'abort'],
  'موافقة': ['accept', 'approve'],
  'رفض': ['reject', 'decline'],
  'إرسال': ['send', 'submit'],
  'استلام': ['receive', 'get'],
  'عرض': ['view', 'show', 'display'],
  'إخفاء': ['hide', 'conceal'],
  'توسيع': ['expand', 'open'],
  'طي': ['collapse', 'close'],
  'تحميل': ['loading', 'spinner'],
  'نجاح': ['success'],
  'خطأ': ['error', 'fail'],
  'تحذير': ['warning', 'warn'],
  'معلومات': ['info', 'information'],
  'بحث': ['search', 'find'],
  'فلترة': ['filter', 'sort'],
  'ترتيب': ['sort', 'order'],
  'تصفح': ['browse', 'navigate'],
  'صفحة': ['page'],
  'قسم': ['section'],
  'فئة': ['category', 'group'],
  'تصنيف': ['classify', 'categorize'],
  'تخصيص': ['customize', 'custom'],
  'إعدادات': ['settings', 'config'],
  'خيارات': ['options', 'preferences'],
  'تفضيلات': ['preferences', 'settings'],
  'ملف شخصي': ['profile', 'account'],
  'حساب': ['account', 'profile'],
  'مستخدم': ['user', 'person'],
  'مشرف': ['admin', 'administrator'],
  'صلاحيات': ['permissions', 'access'],
  'أمان': ['security', 'secure'],
  'تشفير': ['encrypt', 'cipher'],
  'كلمة مرور': ['password', 'pass'],
  // مفاتيح تسجيل الدخول/الخروج/جديد موجودة أعلاه بالفعل
  'نسيان كلمة المرور': ['forgot password', 'reset password'],
  'إعادة تعيين': ['reset', 'restore'],
  'تحديث': ['update', 'refresh'],
  'تحديث البيانات': ['update data', 'refresh data'],
  'حفظ البيانات': ['save data', 'store data'],
  'حذف البيانات': ['delete data', 'remove data'],
  'تصدير': ['export'],
  'استيراد': ['import'],
  'تنزيل': ['download', 'load'],
  'رفع': ['upload'],
  'مشاركة': ['share'],
  'طباعة': ['print'],
  'نسخ': ['copy'],
  'لصق': ['paste'],
  'قص': ['cut'],
  'تراجع': ['undo'],
  'إعادة': ['redo'],
  'تحديث الصفحة': ['refresh page', 'reload'],
  'العودة': ['back', 'return'],
  'التالي': ['next', 'forward'],
  'السابق': ['previous', 'back'],
  'الأول': ['first'],
  'الأخير': ['last'],
  // مفاتيح التالي/السابق مضافة أعلاه
  'الصفحة التالية': ['next page'],
  'الصفحة السابقة': ['previous page'],
  'الصفحة الأولى': ['first page'],
  'الصفحة الأخيرة': ['last page'],
  'عدد الصفحات': ['page count'],
  'إجمالي الصفحات': ['total pages'],
  'الصفحة الحالية': ['current page'],
  'من': ['from'],
  'إلى': ['to'],
  'من أصل': ['of'],
  'نتائج': ['results'],
  'عنصر': ['item', 'element'],
  'عناصر': ['items', 'elements'],
  'عدد': ['count', 'number'],
  'إجمالي': ['total', 'sum'],
  'متوسط': ['average', 'mean'],
  'أقصى': ['maximum', 'max'],
  'أدنى': ['minimum', 'min'],
  'نسبة': ['percentage', 'percent'],
  'معدل': ['rate', 'ratio'],
  'حجم': ['size'],
  'طول': ['length'],
  'العرض (قياس)': ['width'],
  'ارتفاع': ['height'],
  'عمق': ['depth'],
  'مساحة': ['area'],
  'حجم الملف': ['file size'],
  'نوع الملف': ['file type'],
  'اسم الملف': ['file name'],
  'تاريخ الإنشاء': ['creation date', 'created date'],
  'تاريخ التعديل': ['modification date', 'modified date'],
  'تاريخ آخر تحديث': ['last update date'],
  'وقت الإنشاء': ['creation time'],
  'وقت التعديل': ['modification time'],
  'وقت آخر تحديث': ['last update time'],
  'المؤلف': ['author', 'creator'],
  'المحرر': ['editor', 'modifier'],
  'المالك': ['owner'],
  'المشرف': ['admin', 'administrator'],
  'المستخدم': ['user'],
  'الزائر': ['visitor', 'guest'],
  'العضو': ['member'],
  'المشترك': ['subscriber'],
  'العميل': ['client', 'customer'],
  'المورد': ['supplier', 'vendor'],
  'الشركة': ['company', 'organization'],
  'المؤسسة': ['institution', 'organization'],
  'المنظمة': ['organization'],
  'الفريق': ['team'],
  'المجموعة': ['group'],
  'القسم': ['department', 'section'],
  'الفرع': ['branch'],
  'المكتب': ['office'],
  'المقر': ['headquarters'],
  'الموقع': ['location', 'site'],
  'العنوان': ['address'],
  'الهاتف': ['phone', 'telephone'],
  'البريد الإلكتروني': ['email', 'e-mail'],
  'الموقع الإلكتروني': ['website', 'web site'],
  'الرابط': ['link', 'url'],
  'الصفحة الرئيسية': ['home page', 'main page'],
  // مفاتيح الصفحة الرئيسية مضافة أعلاه
  'صفحة الخطأ': ['error page'],
  'صفحة غير موجودة': ['not found page', '404 page'],
  'صفحة غير مصرح بها': ['unauthorized page', '403 page'],
  'صفحة محظورة': ['forbidden page'],
  'صفحة الخادم': ['server page', '500 page'],
  'صفحة الصيانة': ['maintenance page'],
  'صفحة التوثيق': ['documentation page'],
  'صفحة المساعدة': ['help page'],
  'صفحة الدعم': ['support page'],
  'صفحة الاتصال': ['contact page'],
  'صفحة حول': ['about page'],
  'صفحة الخصوصية': ['privacy page'],
  'صفحة الشروط': ['terms page'],
  'صفحة الإعدادات': ['settings page'],
  'صفحة الملف الشخصي': ['profile page'],
  'صفحة الحساب': ['account page'],
  'صفحة الدخول': ['login page'],
  'صفحة التسجيل': ['signup page'],
  'صفحة نسيان كلمة المرور': ['forgot password page'],
  'صفحة إعادة تعيين كلمة المرور': ['reset password page'],
  'صفحة تغيير كلمة المرور': ['change password page'],
  'صفحة تحديث البيانات': ['update data page'],
  'صفحة حذف الحساب': ['delete account page'],
  'صفحة إلغاء الاشتراك': ['unsubscribe page'],
  'صفحة الاشتراك': ['subscription page'],
  'صفحة الدفع': ['payment page'],
  'صفحة الفواتير': ['billing page'],
  'صفحة الطلبات': ['orders page'],
  'صفحة المنتجات': ['products page'],
  'صفحة الخدمات': ['services page'],
  'صفحة الأسعار': ['pricing page'],
  'صفحة العروض': ['offers page'],
  'صفحة الخصومات': ['discounts page'],
  'صفحة الكوبونات': ['coupons page'],
  'صفحة الهدايا': ['gifts page'],
  'صفحة المكافآت': ['rewards page'],
  'صفحة النقاط': ['points page'],
  'صفحة المحفظة': ['wallet page'],
  'صفحة المحفظة الرقمية': ['digital wallet page'],
  'صفحة البطاقات': ['cards page'],
  'صفحة الحسابات البنكية': ['bank accounts page'],
  'صفحة المعاملات': ['transactions page'],
  'صفحة السجل': ['history page'],
  'صفحة التقارير': ['reports page'],
  'صفحة الإحصائيات': ['statistics page'],
  'صفحة التحليلات': ['analytics page'],
  'صفحة لوحة التحكم': ['dashboard page'],
  'صفحة الإدارة': ['admin page'],
  'صفحة المشرفين': ['administrators page'],
  'صفحة المستخدمين': ['users page'],
  'صفحة الصلاحيات': ['permissions page'],
  'صفحة الأدوار': ['roles page'],
  'صفحة المجموعات': ['groups page'],
  'صفحة الفرق': ['teams page'],
  'صفحة الأقسام': ['departments page'],
  'صفحة الفروع': ['branches page'],
  'صفحة المكاتب': ['offices page'],
  'صفحة المواقع': ['locations page'],
  'صفحة العناوين': ['addresses page'],
  'صفحة جهات الاتصال': ['contacts page'],
  'صفحة العملاء': ['customers page'],
  'صفحة الموردين': ['suppliers page'],
  'صفحة الشركاء': ['partners page'],
  'صفحة الموزعين': ['distributors page'],
  'صفحة الوكالات': ['agencies page'],
  // مفاتيح مكررة لصفحات مختلفة تمت إضافتها أعلاه
}

// قاموس عكسي للترجمة من الإنجليزية إلى العربية
export const englishToArabicMapping: Record<string, string[]> = {
  'accordion': ['أكورديون', 'قابل للطي', 'قابل للتوسيع'],
  'button': ['زر', 'أزرار'],
  'text': ['نص', 'نصوص'],
  'input': ['حقل', 'حقول', 'إدخال'],
  'list': ['قائمة', 'قوائم'],
  'table': ['جدول', 'جداول'],
  'card': ['بطاقة', 'بطاقات'],
  'modal': ['نافذة', 'نوافذ', 'حوار'],
  'alert': ['تنبيه', 'تنبيهات'],
  'bar': ['شريط', 'شرائط'],
  'tab': ['تبويب', 'تبويبات'],
  'form': ['نموذج', 'نماذج'],
  'login': ['تسجيل الدخول', 'دخول'],
  'logout': ['تسجيل الخروج', 'خروج'],
  'signup': ['تسجيل جديد', 'إنشاء حساب'],
  'file': ['ملف', 'ملفات'],
  'image': ['صورة', 'صور'],
  'video': ['فيديو', 'فيديوهات'],
  'audio': ['صوت', 'أصوات'],
  'link': ['رابط', 'روابط'],
  'dropdown': ['قائمة منسدلة', 'قوائم منسدلة'],
  'scrollbar': ['شريط التمرير', 'شرائط التمرير'],
  'navbar': ['شريط التنقل', 'شريط الملاحة'],
  'sidebar': ['شريط جانبي', 'شريط جانبي'],
  'footer': ['تذييل', 'تذييلات'],
  'header': ['رأس', 'رؤوس'],
  'content': ['محتوى', 'محتويات'],
  'container': ['حاوية', 'حاويات'],
  'grid': ['شبكة', 'شبكات'],
  'row': ['صف', 'صفوف'],
  'column': ['عمود', 'أعمدة'],
  'divider': ['فاصل', 'فوارق'],
  'icon': ['أيقونة', 'أيقونات'],
  'logo': ['شعار', 'شعارات'],
  'badge': ['علامة', 'علامات'],
  'tooltip': ['تلميح', 'تلميحات'],
  'confirmation': ['تأكيد', 'تأكيدات'],
  'delete': ['حذف', 'حذف'],
  'edit': ['تحرير', 'تعديل'],
  'save': ['حفظ', 'حفظ'],
  'cancel': ['إلغاء', 'إلغاء'],
  'accept': ['موافقة', 'قبول'],
  'reject': ['رفض', 'رفض'],
  'send': ['إرسال', 'إرسال'],
  'receive': ['استلام', 'استقبال'],
  'view': ['عرض', 'مشاهدة'],
  'hide': ['إخفاء', 'إخفاء'],
  'expand': ['توسيع', 'فتح'],
  'collapse': ['طي', 'إغلاق'],
  'loading': ['تحميل', 'جاري التحميل'],
  'success': ['نجاح', 'تم بنجاح'],
  'warning': ['تحذير', 'تحذير'],
  'info': ['معلومات', 'معلومات'],
  'search': ['بحث', 'البحث'],
  'filter': ['فلترة', 'تصفية'],
  'sort': ['ترتيب', 'ترتيب'],
  'browse': ['تصفح', 'تصفح'],
  'page': ['صفحة', 'صفحات'],
  'section': ['قسم', 'أقسام'],
  'category': ['فئة', 'فئات'],
  'customize': ['تخصيص', 'تخصيص'],
  'settings': ['إعدادات', 'إعدادات'],
  'options': ['خيارات', 'خيارات'],
  'preferences': ['تفضيلات', 'تفضيلات'],
  'profile': ['ملف شخصي', 'الملف الشخصي'],
  'account': ['حساب', 'حساب'],
  'user': ['مستخدم', 'مستخدم'],
  'admin': ['مشرف', 'مشرف'],
  'permissions': ['صلاحيات', 'صلاحيات'],
  'security': ['أمان', 'أمان'],
  'password': ['كلمة مرور', 'كلمة المرور'],
  'forgot': ['نسيان', 'نسيان'],
  'reset': ['إعادة تعيين', 'إعادة تعيين'],
  'update': ['تحديث', 'تحديث'],
  'refresh': ['تحديث', 'تحديث'],
  'export': ['تصدير', 'تصدير'],
  'import': ['استيراد', 'استيراد'],
  'download': ['تحميل', 'تحميل'],
  'upload': ['رفع', 'رفع'],
  'share': ['مشاركة', 'مشاركة'],
  'print': ['طباعة', 'طباعة'],
  'copy': ['نسخ', 'نسخ'],
  'paste': ['لصق', 'لصق'],
  'cut': ['قص', 'قص'],
  'undo': ['تراجع', 'تراجع'],
  'redo': ['إعادة', 'إعادة'],
  'back': ['العودة', 'رجوع'],
  'next': ['التالي', 'التالي'],
  'previous': ['السابق', 'السابق'],
  'first': ['الأول', 'الأول'],
  'last': ['الأخير', 'الأخير'],
  'results': ['نتائج', 'النتائج'],
  'item': ['عنصر', 'عناصر'],
  'count': ['عدد', 'العدد'],
  'total': ['إجمالي', 'المجموع'],
  'size': ['حجم', 'الحجم'],
  'date': ['تاريخ', 'التاريخ'],
  'time': ['وقت', 'الوقت'],
  'author': ['مؤلف', 'المؤلف'],
  'editor': ['محرر', 'المحرر'],
  'owner': ['مالك', 'المالك'],
  'member': ['عضو', 'عضو'],
  'team': ['فريق', 'فريق'],
  'group': ['مجموعة', 'مجموعة'],
  'company': ['شركة', 'شركة'],
  'organization': ['منظمة', 'منظمة'],
  'location': ['موقع', 'موقع'],
  'address': ['عنوان', 'عنوان'],
  'phone': ['هاتف', 'هاتف'],
  'email': ['بريد إلكتروني', 'بريد إلكتروني'],
  'website': ['موقع إلكتروني', 'موقع إلكتروني'],
  'home': ['الرئيسية', 'الرئيسية'],
  'main': ['رئيسي', 'رئيسي'],
  'landing': ['هبوط', 'هبوط'],
  'error': ['خطأ', 'خطأ'],
  'not found': ['غير موجود', 'غير موجود'],
  'unauthorized': ['غير مصرح', 'غير مصرح'],
  'forbidden': ['محظور', 'محظور'],
  'server': ['خادم', 'خادم'],
  'maintenance': ['صيانة', 'صيانة'],
  'documentation': ['توثيق', 'توثيق'],
  'help': ['مساعدة', 'مساعدة'],
  'support': ['دعم', 'دعم'],
  'contact': ['اتصال', 'اتصال'],
  'about': ['حول', 'حول'],
  'privacy': ['خصوصية', 'خصوصية'],
  'terms': ['شروط', 'شروط'],
  'dashboard': ['لوحة تحكم', 'لوحة تحكم'],
  'administration': ['إدارة', 'إدارة'],
  'users': ['مستخدمين', 'مستخدمين'],
  'roles': ['أدوار', 'أدوار'],
  'groups': ['مجموعات', 'مجموعات'],
  'teams': ['فرق', 'فرق'],
  'departments': ['أقسام', 'أقسام'],
  'branches': ['فروع', 'فروع'],
  'offices': ['مكاتب', 'مكاتب'],
  'locations': ['مواقع', 'مواقع'],
  'addresses': ['عناوين', 'عناوين'],
  'contacts': ['جهات اتصال', 'جهات اتصال'],
  'customers': ['عملاء', 'عملاء'],
  'suppliers': ['موردين', 'موردين'],
  'partners': ['شركاء', 'شركاء'],
  'distributors': ['موزعين', 'موزعين'],
  'agencies': ['وكالات', 'وكالات'],
  'headquarters': ['مقرات', 'مقرات'],
  'sites': ['مواقع', 'مواقع']
}

// دالة لتحويل النص العربي إلى إنجليزي للبحث
export function translateArabicToEnglish(text: string): string[] {
  const words = text.toLowerCase().split(/\s+/)
  const translations: string[] = []
  
  for (const word of words) {
    if (arabicToEnglishMapping[word]) {
      translations.push(...arabicToEnglishMapping[word])
    } else {
      translations.push(word)
    }
  }
  
  return translations
}

// دالة لتحويل النص الإنجليزي إلى عربي للبحث
export function translateEnglishToArabic(text: string): string[] {
  const words = text.toLowerCase().split(/\s+/)
  const translations: string[] = []
  
  for (const word of words) {
    if (englishToArabicMapping[word]) {
      translations.push(...englishToArabicMapping[word])
    } else {
      translations.push(word)
    }
  }
  
  return translations
}

// دالة للبحث باللغتين
export function createBilingualSearchTerms(text: string): string[] {
  const originalTerms = text.toLowerCase().split(/\s+/)
  const arabicTranslations = translateArabicToEnglish(text)
  const englishTranslations = translateEnglishToArabic(text)
  
  return [...new Set([...originalTerms, ...arabicTranslations, ...englishTranslations])]
}

